[package]
name = "orpheus-lang"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
comfy-table.workspace = true
crossterm.workspace = true
midir = "0.10"
orpheus-dsp.workspace = true
orpheus-pattern.workspace = true
pest = "2.8.6"
pest_derive = "2.8.6"
ratatui.workspace = true
unicode-width = "0.2.0"

[dev-dependencies]
hound.workspace = true
proptest = { workspace = true }
serde_json = "1"
tempfile = "3.27.0"
