[workspace]
members = [
    "crates/orpheus-dsp",
    "crates/orpheus-lang",
    "crates/orpheus-pattern",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1"
cpal = "0.15"
crossterm = "0.28"
flacenc = "0.5"
hound = "3.5"
orpheus-dsp = { path = "crates/orpheus-dsp" }
orpheus-lang = { path = "crates/orpheus-lang" }
orpheus-pattern = { path = "crates/orpheus-pattern" }
proptest = "1.6.0"
ratatui = "0.29"
rtrb = "0.3"
thiserror = "2"

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"

[package]
name = "orpheus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
cpal.workspace = true
orpheus-dsp.workspace = true
orpheus-lang.workspace = true
orpheus-pattern.workspace = true

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
