[package]
name = "orpheus-dsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
cpal.workspace = true
flacenc.workspace = true
hound.workspace = true
orpheus-pattern.workspace = true
rtrb.workspace = true
thiserror.workspace = true
loom.workspace = true
