//! The `chuck_export` module provides an exporter to `ChucK` `.ck` scripts.
//!
//! This exporter generates a strongly-timed `.ck` script for the `ChucK`
//! audio programming language. It maps number patterns to a `SinOsc`
//! and sample patterns to a `SndBuf`, scheduling them over time.

use std::io::Write;
use std::path::Path;

use crate::eval::{EvalError, render_span};
use crate::value::{NumberPatternValue, SamplePatternValue};

// Assume 120 BPM, 4 beats per cycle -> 1 cycle = 2.0 seconds.
const SECONDS_PER_CYCLE: f64 = 2.0;

/// Exports a number pattern's evaluated events to a `ChucK` script.
///
/// Number patterns are assumed to represent MIDI pitches, which are
/// played using a basic sine oscillator (`SinOsc`).
///
/// # Examples
///
/// ```no_run
/// use orpheus_lang::{ReplMode, eval_module, export_number_pattern_to_chuck};
///
/// let env = eval_module("x = 60 62 64", ReplMode::Loose).unwrap();
/// let pattern = env.get("x").unwrap().as_number_pattern().unwrap();
///
/// let path = std::env::temp_dir().join("export_num.ck");
/// export_number_pattern_to_chuck(pattern, &path, 2).unwrap();
/// ```
///
/// # Errors
///
/// Returns [`EvalError`] if pattern querying fails or if the file cannot be written.
pub fn export_number_pattern_to_chuck(
    pattern: &NumberPatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;
    events.sort_by(|a, b| a.part.start().cmp(b.part.start()));

    let path = path.as_ref();
    let mut file = std::fs::File::create(path).map_err(|e| EvalError::new(e.to_string()))?;

    writeln!(file, "// Orpheus `ChucK` Export")?;
    writeln!(file, "// Generated by Nova 🌟")?;
    writeln!(file, "// =======================")?;
    writeln!(file, "// Cycles: {cycle_count}")?;
    writeln!(file)?;

    writeln!(file, "SinOsc osc => dac;")?;
    writeln!(file, "0 => osc.gain;")?;
    writeln!(file)?;

    let mut current_time_sec = 0.0;

    for event in &events {
        let start_sec = f64::from(event.part.start()) * SECONDS_PER_CYCLE;
        let end_sec = f64::from(event.part.end()) * SECONDS_PER_CYCLE;
        let mut duration_sec = end_sec - start_sec;

        if duration_sec < 0.01 {
            duration_sec = 0.01;
        }

        let sleep_before_sec = if start_sec > current_time_sec {
            start_sec - current_time_sec
        } else {
            0.0
        };
        current_time_sec = start_sec + duration_sec;

        let midi_note = event.value;

        if sleep_before_sec > 0.001 {
            writeln!(file, "{sleep_before_sec:.3}::second => now;")?;
        }

        writeln!(file, "Std.mtof({midi_note:.3}) => osc.freq;")?;
        writeln!(file, "0.5 => osc.gain;")?;
        writeln!(file, "{duration_sec:.3}::second => now;")?;
        writeln!(file, "0 => osc.gain;")?;
    }

    #[allow(clippy::cast_precision_loss)]
    let total_time_sec = (cycle_count as f64) * SECONDS_PER_CYCLE;
    if total_time_sec > current_time_sec {
        let final_sleep = total_time_sec - current_time_sec;
        if final_sleep > 0.001 {
            writeln!(file, "{final_sleep:.3}::second => now;")?;
        }
    }

    Ok(())
}

/// Exports a sample pattern's evaluated events to a `ChucK` script.
///
/// Sample patterns use `SndBuf` to load and play wav files.
/// Since `ChucK` requires file paths, this assumes samples are available
/// in a `./samples/` directory relative to where the `ChucK` script is run.
///
/// # Examples
///
/// ```no_run
/// use orpheus_lang::{ReplMode, eval_module, export_sample_pattern_to_chuck};
///
/// let env = eval_module("x = bd sn", ReplMode::Loose).unwrap();
/// let pattern = env.get("x").unwrap().as_sample_pattern().unwrap();
///
/// let path = std::env::temp_dir().join("export_sample.ck");
/// export_sample_pattern_to_chuck(pattern, &path, 2).unwrap();
/// ```
///
/// # Errors
///
/// Returns [`EvalError`] if pattern querying fails or if the file cannot be written.
pub fn export_sample_pattern_to_chuck(
    pattern: &SamplePatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;
    events.sort_by(|a, b| a.part.start().cmp(b.part.start()));

    let path = path.as_ref();
    let mut file = std::fs::File::create(path).map_err(|e| EvalError::new(e.to_string()))?;

    writeln!(file, "// Orpheus `ChucK` Export (Samples)")?;
    writeln!(file, "// Generated by Nova 🌟")?;
    writeln!(file, "// =======================")?;
    writeln!(file, "// Cycles: {cycle_count}")?;
    writeln!(
        file,
        "// Note: Ensure a 'samples' directory exists next to this file"
    )?;
    writeln!(file)?;

    writeln!(file, "SndBuf buf => dac;")?;
    writeln!(file, "0 => buf.gain;")?;
    writeln!(file)?;

    let mut current_time_sec = 0.0;

    for event in &events {
        let start_sec = f64::from(event.part.start()) * SECONDS_PER_CYCLE;
        let end_sec = f64::from(event.part.end()) * SECONDS_PER_CYCLE;
        let mut duration_sec = end_sec - start_sec;

        if duration_sec < 0.01 {
            duration_sec = 0.01;
        }

        let sleep_before_sec = if start_sec > current_time_sec {
            start_sec - current_time_sec
        } else {
            0.0
        };
        current_time_sec = start_sec + duration_sec;

        let sample_name = event.value.sample();

        if sleep_before_sec > 0.001 {
            writeln!(file, "{sleep_before_sec:.3}::second => now;")?;
        }

        writeln!(file, "\"samples/{sample_name}.wav\" => buf.read;")?;
        writeln!(file, "0 => buf.pos;")?;
        writeln!(file, "0.5 => buf.gain;")?;
        writeln!(file, "{duration_sec:.3}::second => now;")?;
        writeln!(file, "0 => buf.gain;")?;
    }

    #[allow(clippy::cast_precision_loss)]
    let total_time_sec = (cycle_count as f64) * SECONDS_PER_CYCLE;
    if total_time_sec > current_time_sec {
        let final_sleep = total_time_sec - current_time_sec;
        if final_sleep > 0.001 {
            writeln!(file, "{final_sleep:.3}::second => now;")?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ReplMode, eval_module};
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    static UNIQUE_TEMP_ID: AtomicU64 = AtomicU64::new(0);

    fn unique_temp_suffix() -> String {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let counter = UNIQUE_TEMP_ID.fetch_add(1, Ordering::Relaxed);
        format!("{timestamp}-{counter}")
    }

    #[test]
    fn chuck_exporter_generates_number_pattern() {
        let source = "pattern = 60 62 64";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("pattern").unwrap().as_number_pattern().unwrap();

        let path =
            std::env::temp_dir().join(format!("test_chuck_output_{}.ck", unique_temp_suffix()));
        export_number_pattern_to_chuck(pattern, &path, 1).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("// Orpheus `ChucK` Export"));
        assert!(content.contains("SinOsc osc => dac;"));
        assert!(content.contains("Std.mtof(60.000) => osc.freq;"));
        assert!(content.contains("0.5 => osc.gain;"));
        assert!(content.contains("second => now;"));

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn chuck_exporter_generates_sample_pattern() {
        let source = "pattern = bd sn";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("pattern").unwrap().as_sample_pattern().unwrap();

        let path = std::env::temp_dir().join(format!(
            "test_chuck_output_sample_{}.ck",
            unique_temp_suffix()
        ));
        export_sample_pattern_to_chuck(pattern, &path, 1).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("// Orpheus `ChucK` Export (Samples)"));
        assert!(content.contains("SndBuf buf => dac;"));
        assert!(content.contains("\"samples/bd.wav\" => buf.read;"));
        assert!(content.contains("0 => buf.pos;"));
        assert!(content.contains("second => now;"));

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn export_cycle_count_zero_returns_error() {
        let module = eval_module("pat = 1 2", ReplMode::Loose).unwrap();
        let pat = module.get("pat").unwrap().as_number_pattern().unwrap();

        assert_eq!(
            super::export_number_pattern_to_chuck(pat, "test.ck", 0)
                .unwrap_err()
                .to_string(),
            "exporting requires at least one cycle"
        );

        let module2 = eval_module("pat2 = bd", ReplMode::Loose).unwrap();
        let pat2 = module2.get("pat2").unwrap().as_sample_pattern().unwrap();

        assert_eq!(
            super::export_sample_pattern_to_chuck(pat2, "test_sample.ck", 0)
                .unwrap_err()
                .to_string(),
            "exporting requires at least one cycle"
        );
    }
}
