//! The `csound_export` module provides an exporter to Csound Score (`.sco`) format.
//!
//! This exporter translates evaluated number patterns into Csound `i` statements,
//! which schedule instrument events in absolute time. The output includes a basic
//! comment header detailing how to use it with a simple `.orc` orchestra file.

use std::io::Write;
use std::path::Path;

use crate::eval::{EvalError, render_span};
use crate::value::NumberPatternValue;

// Assume 120 BPM, 4 beats per cycle -> 1 cycle = 2.0 seconds
const SECONDS_PER_CYCLE: f64 = 2.0;

/// Converts a MIDI note number to its corresponding frequency in Hertz.
#[must_use]
pub fn midi_to_hz(midi: f64) -> f64 {
    440.0 * ((midi - 69.0) / 12.0).exp2()
}

/// Exports a number pattern's evaluated events to a Csound Score (`.sco`) file.
///
/// # Examples
///
/// ```no_run
/// use orpheus_lang::{ReplMode, eval_module};
/// use orpheus_lang::csound_export::export_number_pattern_to_csound;
///
/// let env = eval_module("melody = 60 62 64", ReplMode::Loose).unwrap();
/// let pattern = env.get("melody").unwrap().as_number_pattern().unwrap();
///
/// let path = std::env::temp_dir().join("output.sco");
/// export_number_pattern_to_csound(pattern, &path, 2, 1).unwrap();
/// ```
///
/// # Errors
///
/// Returns [`EvalError`] if pattern querying fails or if the file cannot be written.
pub fn export_number_pattern_to_csound(
    pattern: &NumberPatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
    instrument: u32,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;
    events.sort_by(|a, b| a.part.start().cmp(b.part.start()));

    let path = path.as_ref();
    let mut file = std::fs::File::create(path).map_err(|e| EvalError::new(e.to_string()))?;

    writeln!(file, "; Orpheus Csound Score Export")?;
    writeln!(file, "; ===========================")?;
    writeln!(file, "; Generated by Nova")?;
    writeln!(file, ";")?;
    writeln!(
        file,
        "; To play this score, create a simple 'orchestra.orc' file:"
    )?;
    writeln!(file, "; instr {instrument}")?;
    writeln!(file, ";   a1 oscil 0.5, p4, 1")?;
    writeln!(file, ";   out a1")?;
    writeln!(file, "; endin")?;
    writeln!(file, "; and run: csound orchestra.orc {}", path.display())?;
    writeln!(file)?;

    // Add a basic sine wave table just in case the instrument wants to use it (f1)
    writeln!(
        file,
        "; Generate a sine wave table (f1) for basic oscillators"
    )?;
    writeln!(file, "f 1 0 16384 10 1")?;
    writeln!(file)?;

    writeln!(file, "; i p1 p2 p3 p4")?;
    writeln!(
        file,
        "; p1 = instrument, p2 = start time (s), p3 = duration (s), p4 = frequency (Hz)"
    )?;

    for event in events {
        let start_s = f64::from(event.part.start()) * SECONDS_PER_CYCLE;
        let end_s = f64::from(event.part.end()) * SECONDS_PER_CYCLE;
        let duration_s = end_s - start_s;

        let freq = midi_to_hz(event.value);

        writeln!(
            file,
            "i {instrument} {start_s:.3} {duration_s:.3} {freq:.3}"
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ReplMode, eval_module};

    #[test]
    fn csound_exporter_generates_score() {
        let source = "pattern = 60 64";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("pattern").unwrap().as_number_pattern().unwrap();

        let path = std::env::temp_dir().join("test_csound_output.sco");
        export_number_pattern_to_csound(pattern, &path, 1, 1).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("; Orpheus Csound Score Export"));
        assert!(content.contains("f 1 0 16384 10 1"));
        assert!(content.contains("i 1 0.000 1.000 261.626")); // Midi 60 -> ~261.63 Hz
        assert!(content.contains("i 1 1.000 1.000 329.628")); // Midi 64 -> ~329.63 Hz

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn export_cycle_count_zero_returns_error() {
        let module = eval_module("pat = 1 2", ReplMode::Loose).unwrap();
        let pat = module.get("pat").unwrap().as_number_pattern().unwrap();

        assert_eq!(
            super::export_number_pattern_to_csound(pat, "test.sco", 0, 1)
                .unwrap_err()
                .to_string(),
            "exporting requires at least one cycle"
        );
    }
}
