//! The `minecraft_export` module provides an exporter to Minecraft `.mcfunction` files.
//!
//! This exporter translates evaluated number patterns (representing MIDI pitches)
//! into Minecraft `/playsound` commands. This allows Orpheus to be used as a
//! composition tool for Minecraft datapacks and custom maps.

use std::io::Write;
use std::path::Path;

use crate::eval::EvalError;
use crate::value::NumberPatternValue;

// Assuming 120 BPM, 4 beats per cycle -> 1 cycle = 2.0 seconds
const SECONDS_PER_CYCLE: f64 = 2.0;
const TICKS_PER_SECOND: f64 = 20.0;

/// Exports a number pattern's evaluated events to a Minecraft function file.
///
/// Number patterns are assumed to represent MIDI pitch. The exporter translates
/// the timing into Minecraft game ticks and the pitch into playback speeds
/// for the `playsound` command.
///
/// # Examples
///
/// ```
/// use orpheus_lang::{ReplMode, eval_module};
/// use orpheus_lang::export_number_pattern_to_minecraft;
///
/// let env = eval_module("x = 60 62 64", ReplMode::Loose).unwrap();
/// let pattern = env.get("x").unwrap().as_number_pattern().unwrap();
///
/// let path = std::env::temp_dir().join("export_music.mcfunction");
/// export_number_pattern_to_minecraft(pattern, &path, 2).unwrap();
/// ```
///
/// # Errors
///
/// Returns [`EvalError`] if pattern querying fails or if the file cannot be written.
#[allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss
)]
pub fn export_number_pattern_to_minecraft(
    pattern: &NumberPatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    let mut events = crate::export::query_number_pattern_events(pattern, cycle_count)?;
    events.sort_unstable_by(|a, b| a.part.start().cmp(b.part.start()));

    let path = path.as_ref();
    let mut file = std::fs::File::create(path)?;

    writeln!(file, "# Orpheus Minecraft Exporter")?;
    writeln!(file, "# Generated by Nova")?;
    writeln!(
        file,
        "# Usage: Create a scoreboard objective 'orpheus_timer' and increment it every tick."
    )?;
    writeln!(file, "# Execute this function every tick.")?;
    writeln!(file)?;

    for event in &events {
        let start = f64::from(event.part.start());
        let ticks = (start * SECONDS_PER_CYCLE * TICKS_PER_SECOND).round() as u64;

        // Minecraft pitch ranges from 0.5 to 2.0. Base pitch 1.0 is roughly F#4 (MIDI 66) for noteblocks,
        // but MIDI 60 (C4) as 1.0 is a common convention for ease. We'll use 60 as 1.0.
        let pitch = ((event.value - 60.0) / 12.0).exp2();

        let mut mc_pitch = pitch;
        mc_pitch = mc_pitch.clamp(0.5, 2.0);

        writeln!(
            file,
            "execute if score @s orpheus_timer matches {ticks} run playsound block.note_block.harp master @a ~ ~ ~ 1.0 {mc_pitch:.3}"
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ReplMode, eval_module};

    #[test]
    fn minecraft_exporter_generates_valid_commands() {
        let source = "melody = 60 72";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("melody").unwrap().as_number_pattern().unwrap();

        let path = std::env::temp_dir().join("test_output.mcfunction");
        export_number_pattern_to_minecraft(pattern, &path, 1).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("run playsound block.note_block.harp master @a ~ ~ ~ 1.0 1.000"));
        assert!(content.contains("run playsound block.note_block.harp master @a ~ ~ ~ 1.0 2.000"));
        assert!(content.contains("matches 0 run playsound"));
        assert!(content.contains("matches 20 run playsound"));
    }

    #[test]
    fn export_cycle_count_zero_returns_error() {
        let module = eval_module("pat = 60 62", ReplMode::Loose).unwrap();
        let pat = module.get("pat").unwrap().as_number_pattern().unwrap();

        assert_eq!(
            super::export_number_pattern_to_minecraft(pat, "test.mcfunction", 0)
                .unwrap_err()
                .to_string(),
            "exporting requires at least one cycle"
        );
    }
}
