//! The `scad_export` module provides export functionality for `OpenSCAD` scripts.
//!
//! This exporter visualizes a number pattern (like a melody) as a 3D music box
//! cylinder, mapping time to radial angle and pitch value to the Z-axis.

use std::io::Write;
use std::path::Path;

use crate::eval::{EvalError, render_span};
use crate::value::NumberPatternValue;

/// Exports a number pattern's evaluated events to an `OpenSCAD` 3D model.
///
/// The model is an interactive 3D music box drum where the Z-axis corresponds
/// to value (pitch) and the radial angle corresponds to pattern time.
///
/// # Examples
///
/// ```
/// use orpheus_lang::{ReplMode, eval_module, export_number_pattern_to_scad};
///
/// let env = eval_module("melody = 0 2 4 7", ReplMode::Loose).unwrap();
/// let pattern = env.get("melody").unwrap().as_number_pattern().unwrap();
///
/// let path = std::env::temp_dir().join("music_box.scad");
/// export_number_pattern_to_scad(pattern, &path, 1).unwrap();
/// ```
///
/// # Errors
///
/// Returns [`EvalError`] if pattern querying fails or if the file cannot be written.
#[allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    clippy::cast_sign_loss
)]
pub fn export_number_pattern_to_scad(
    pattern: &NumberPatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;
    events.sort_by(|a, b| a.part.start().cmp(b.part.start()));

    let path = path.as_ref();
    let mut file = std::fs::File::create(path)?;

    let mut min_val = f64::INFINITY;
    let mut max_val = f64::NEG_INFINITY;
    for event in &events {
        if event.value < min_val {
            min_val = event.value;
        }
        if event.value > max_val {
            max_val = event.value;
        }
    }

    if min_val.is_infinite() || max_val.is_infinite() {
        min_val = 0.0;
        max_val = 1.0;
    } else if (max_val - min_val).abs() < f64::EPSILON {
        min_val -= 0.5;
        max_val += 0.5;
    }

    let radius = 30.0;
    let height = 50.0;
    let thickness = 2.0;
    let peg_radius = 1.5;
    let peg_length = 4.0;

    writeln!(file, "// Orpheus Pattern Music Box")?;
    writeln!(file, "// Generated by Nova")?;
    writeln!(file)?;
    writeln!(file, "$fn = 60;")?;
    writeln!(file)?;

    // Draw the main cylinder (the drum)
    writeln!(file, "difference() {{")?;
    writeln!(
        file,
        "    cylinder(h = {height:.3}, r = {radius:.3}, center = true);"
    )?;
    writeln!(
        file,
        "    cylinder(h = {:.3}, r = {:.3}, center = true);",
        height + 1.0,
        radius - thickness
    )?;
    writeln!(file, "}}")?;
    writeln!(file)?;

    // Draw the pegs
    for event in &events {
        let start = f64::from(event.part.start());

        // Map time to angle (0 to 360 degrees across cycle_count)
        let fraction = start / (cycle_count as f64);
        let angle = fraction * 360.0;

        // Map value to Z axis
        let normalized_val = (event.value - min_val) / (max_val - min_val);
        // Map to -height/2 + margin to height/2 - margin
        let margin = 5.0;
        let z = normalized_val.mul_add(2.0_f64.mul_add(-margin, height), -(height / 2.0 - margin));

        // Convert cylindrical to cartesian for the peg position
        let rad = angle.to_radians();
        let x = radius * rad.cos();
        let mut y = radius * rad.sin();
        if y.abs() < 1e-10 {
            y = 0.0;
        }

        // We rotate the peg so it points outward radially
        writeln!(file, "translate([{x:.3}, {y:.3}, {z:.3}])")?;
        writeln!(file, "rotate([0, 90, {angle:.3}])")?;
        writeln!(
            file,
            "cylinder(h = {peg_length:.3}, r = {peg_radius:.3}, center = false);"
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ReplMode, eval_module};

    #[test]
    fn scad_exporter_generates_valid_openscad() {
        let source = "melody = 0 12";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("melody").unwrap().as_number_pattern().unwrap();

        let path = std::env::temp_dir().join("test_output.scad");
        export_number_pattern_to_scad(pattern, &path, 1).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("cylinder(h = 50.000, r = 30.000, center = true);"));
        // First peg at time=0, value=0 (mapped to z ~ -20)
        assert!(content.contains("translate([30.000, 0.000, -20.000])"));
        assert!(content.contains("rotate([0, 90, 0.000])"));
        // Second peg at time=0.5, value=12 (mapped to z ~ 20, angle = 180)
        assert!(content.contains("translate([-30.000, 0.000, 20.000])"));
        assert!(content.contains("rotate([0, 90, 180.000])"));
    }

    #[test]
    fn export_cycle_count_zero_returns_error() {
        let module = eval_module("pat = 1 2", ReplMode::Loose).unwrap();
        let pat = module.get("pat").unwrap().as_number_pattern().unwrap();

        assert_eq!(
            super::export_number_pattern_to_scad(pat, "test.scad", 0)
                .unwrap_err()
                .to_string(),
            "exporting requires at least one cycle"
        );
    }
}
