//! The `sonic_pi` module provides functions to export Orpheus patterns to Sonic Pi Ruby scripts.
//!
//! This enables taking a generative pattern created in Orpheus and rendering it out
//! as an executable `.rb` file that can be pasted directly into Sonic Pi.

use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

use crate::eval::{EvalError, render_span};
use crate::value::{NumberPatternValue, SamplePatternValue};

/// Exports a sample pattern's evaluated events to a Sonic Pi Ruby script.
///
/// # Errors
///
/// Returns [`EvalError`] if pattern querying fails, `cycle_count` is 0,
/// or if writing the output file fails.
///
/// # Examples
///
/// ```
/// use orpheus_lang::{ReplMode, eval_module, export_sample_pattern_to_sonic_pi};
///
/// let env = eval_module("x = bd sn", ReplMode::Loose).unwrap();
/// let pattern = env.get("x").unwrap().as_sample_pattern().unwrap();
///
/// let path = std::env::temp_dir().join("export_sample_pattern.rb");
/// export_sample_pattern_to_sonic_pi(pattern, &path, 2).unwrap();
/// ```
pub fn export_sample_pattern_to_sonic_pi(
    pattern: &SamplePatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;

    let file = File::create(path).map_err(|e| EvalError::new(e.to_string()))?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "# Generated by Orpheus").map_err(|e| EvalError::new(e.to_string()))?;
    writeln!(
        writer,
        "use_bpm 120 # Default Orpheus BPM, 1 cycle = 2 seconds"
    )
    .map_err(|e| EvalError::new(e.to_string()))?;
    writeln!(writer).map_err(|e| EvalError::new(e.to_string()))?;

    writeln!(writer, "in_thread do").map_err(|e| EvalError::new(e.to_string()))?;

    events.sort_by(|a, b| a.part.start().cmp(b.part.start()));

    let mut current_time = 0.0;

    for event in events {
        let start_time_cycles = f64::from(event.part.start());
        let start_time_beats = start_time_cycles * 4.0;

        if start_time_beats > current_time + f64::EPSILON {
            writeln!(writer, "  sleep {:.4}", start_time_beats - current_time)
                .map_err(|e| EvalError::new(e.to_string()))?;
            current_time = start_time_beats;
        }

        let sample_name = map_sample_to_sonic_pi(event.value.sample());
        writeln!(writer, "  sample :{sample_name}").map_err(|e| EvalError::new(e.to_string()))?;
    }

    writeln!(writer, "end").map_err(|e| EvalError::new(e.to_string()))?;

    Ok(())
}

/// Exports a number pattern's evaluated events to a Sonic Pi Ruby script.
///
/// # Errors
///
/// Returns [`EvalError`] if pattern querying fails, `cycle_count` is 0,
/// or if writing the output file fails.
///
/// # Examples
///
/// ```
/// use orpheus_lang::{ReplMode, eval_module, export_number_pattern_to_sonic_pi};
///
/// let env = eval_module("x = 60 62 64", ReplMode::Loose).unwrap();
/// let pattern = env.get("x").unwrap().as_number_pattern().unwrap();
///
/// let path = std::env::temp_dir().join("export_number_pattern.rb");
/// export_number_pattern_to_sonic_pi(pattern, &path, 2).unwrap();
/// ```
pub fn export_number_pattern_to_sonic_pi(
    pattern: &NumberPatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;

    let file = File::create(path).map_err(|e| EvalError::new(e.to_string()))?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "# Generated by Orpheus").map_err(|e| EvalError::new(e.to_string()))?;
    writeln!(writer, "use_bpm 120").map_err(|e| EvalError::new(e.to_string()))?;
    writeln!(writer, "use_synth :beep").map_err(|e| EvalError::new(e.to_string()))?;
    writeln!(writer).map_err(|e| EvalError::new(e.to_string()))?;

    writeln!(writer, "in_thread do").map_err(|e| EvalError::new(e.to_string()))?;

    events.sort_by(|a, b| a.part.start().cmp(b.part.start()));

    let mut current_time = 0.0;

    for event in events {
        let start_time_cycles = f64::from(event.part.start());
        let start_time_beats = start_time_cycles * 4.0;

        if start_time_beats > current_time + f64::EPSILON {
            writeln!(writer, "  sleep {:.4}", start_time_beats - current_time)
                .map_err(|e| EvalError::new(e.to_string()))?;
            current_time = start_time_beats;
        }

        writeln!(writer, "  play {:.4}", event.value).map_err(|e| EvalError::new(e.to_string()))?;
    }

    writeln!(writer, "end").map_err(|e| EvalError::new(e.to_string()))?;

    Ok(())
}

fn map_sample_to_sonic_pi(sample: &str) -> &'static str {
    match sample {
        "bd" => "bd_haus",
        "sn" => "sn_dolf",
        "hh" => "drum_cymbal_closed",
        "cp" => "sn_generic",
        "saw" => "synth_saw",
        "pulse" => "synth_pulse",
        "tri" => "synth_tri",
        "noise" => "guit_em9",
        _ => "elec_blip",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ReplMode, eval_module};
    use std::fs;

    #[test]
    fn export_sample_pattern_to_sonic_pi_works() {
        let source = "pattern = bd sn";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("pattern").unwrap().as_sample_pattern().unwrap();

        let path = std::env::temp_dir().join("test_sonic_pi_sample.rb");
        export_sample_pattern_to_sonic_pi(pattern, &path, 1).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("use_bpm 120"));
        assert!(content.contains("in_thread do"));
        assert!(content.contains("sample :bd_haus"));
        assert!(content.contains("sample :sn_dolf"));
        assert!(content.contains("sleep 2.0000"));
    }

    #[test]
    fn export_number_pattern_to_sonic_pi_works() {
        let source = "pattern = 60 62 64";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("pattern").unwrap().as_number_pattern().unwrap();

        let path = std::env::temp_dir().join("test_sonic_pi_number.rb");
        export_number_pattern_to_sonic_pi(pattern, &path, 1).unwrap();

        let content = fs::read_to_string(&path).unwrap();
        assert!(content.contains("use_bpm 120"));
        assert!(content.contains("use_synth :beep"));
        assert!(content.contains("play 60.0000"));
        assert!(content.contains("play 62.0000"));
        assert!(content.contains("play 64.0000"));
    }
}
