//! The `tonejs_export` module provides an exporter to Tone.js JavaScript files.
//!
//! This exporter generates a `.js` module that uses the Tone.js library
//! to synthesize and play the evaluated pattern.

use std::io::Write;
use std::path::Path;

use crate::eval::{EvalError, render_span};
use crate::value::{NumberPatternValue, SamplePatternValue};

const SECONDS_PER_CYCLE: f64 = 2.0;

/// Exports a sample pattern's evaluated events to a Tone.js script.
///
/// # Errors
/// Returns [`EvalError`] if pattern querying fails or if the file cannot be written.
pub fn export_sample_pattern_to_tonejs(
    pattern: &SamplePatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;
    events.sort_unstable_by(|a, b| a.part.start().cmp(b.part.start()));

    let path = path.as_ref();
    let mut file = std::fs::File::create(path)?;

    writeln!(file, "// Generated by Orpheus")?;
    writeln!(file, "export async function playPattern() {{")?;
    writeln!(
        file,
        "    if (typeof Tone === 'undefined') throw new Error('Tone.js is required');"
    )?;
    writeln!(file, "    await Tone.start();")?;
    writeln!(file, "    const now = Tone.now();")?;
    writeln!(
        file,
        "    const kick = new Tone.MembraneSynth().toDestination();"
    )?;
    writeln!(
        file,
        "    const snare = new Tone.NoiseSynth().toDestination();"
    )?;
    writeln!(
        file,
        "    const hat = new Tone.MetalSynth().toDestination();"
    )?;

    for event in &events {
        let start_sec = f64::from(event.part.start()) * SECONDS_PER_CYCLE;
        let sample = event.value.sample();

        let code = match sample {
            "bd" | "kick" => {
                format!("kick.triggerAttackRelease(\"C1\", \"8n\", now + {start_sec:.3});")
            }
            "sn" | "snare" | "cp" | "clap" => {
                format!("snare.triggerAttackRelease(\"16n\", now + {start_sec:.3});")
            }
            "hh" | "hat" | "oh" | "cr" | "rd" => {
                format!("hat.triggerAttackRelease(\"32n\", now + {start_sec:.3});")
            }
            _ => format!("// unknown sample: {sample} at {start_sec:.3}"),
        };
        writeln!(file, "    {code}")?;
    }

    writeln!(file, "}}")?;
    Ok(())
}

/// Exports a number pattern's evaluated events to a Tone.js script.
///
/// # Errors
/// Returns [`EvalError`] if pattern querying fails or if the file cannot be written.
pub fn export_number_pattern_to_tonejs(
    pattern: &NumberPatternValue,
    path: impl AsRef<Path>,
    cycle_count: u64,
) -> Result<(), EvalError> {
    if cycle_count == 0 {
        return Err(EvalError::new("exporting requires at least one cycle"));
    }

    let span = render_span(cycle_count)?;
    let mut events = pattern.try_query(&span)?;
    events.sort_unstable_by(|a, b| a.part.start().cmp(b.part.start()));

    let path = path.as_ref();
    let mut file = std::fs::File::create(path)?;

    writeln!(file, "// Generated by Orpheus")?;
    writeln!(file, "export async function playPattern() {{")?;
    writeln!(
        file,
        "    if (typeof Tone === 'undefined') throw new Error('Tone.js is required');"
    )?;
    writeln!(file, "    await Tone.start();")?;
    writeln!(file, "    const now = Tone.now();")?;
    writeln!(
        file,
        "    const synth = new Tone.PolySynth(Tone.Synth).toDestination();"
    )?;

    for event in &events {
        let start_sec = f64::from(event.part.start()) * SECONDS_PER_CYCLE;
        let dur_sec =
            (f64::from(event.part.end()) - f64::from(event.part.start())) * SECONDS_PER_CYCLE;
        // number represents MIDI pitch
        let midi = event.value;
        let hz = 440.0 * ((midi - 69.0) / 12.0).exp2();

        writeln!(
            file,
            "    synth.triggerAttackRelease({hz:.3}, {dur_sec:.3}, now + {start_sec:.3});"
        )?;
    }

    writeln!(file, "}}")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ReplMode, eval_module};

    #[test]
    fn tonejs_exporter_generates_valid_format_for_samples() {
        let source = "x = bd sn hh";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("x").unwrap().as_sample_pattern().unwrap();

        let path = std::env::temp_dir().join("test_output.js");
        export_sample_pattern_to_tonejs(pattern, &path, 1).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("export async function playPattern()"));
        assert!(content.contains("kick.triggerAttackRelease"));
        assert!(content.contains("snare.triggerAttackRelease"));
        assert!(content.contains("hat.triggerAttackRelease"));
    }

    #[test]
    fn tonejs_exporter_generates_valid_format_for_numbers() {
        let source = "x = 60 62 64";
        let module = eval_module(source, ReplMode::Loose).unwrap();
        let pattern = module.get("x").unwrap().as_number_pattern().unwrap();

        let path = std::env::temp_dir().join("test_number_output.js");
        export_number_pattern_to_tonejs(pattern, &path, 1).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("export async function playPattern()"));
        assert!(content.contains("synth.triggerAttackRelease(261.626")); // MIDI 60
    }
}
